name: mavenwebapp
services:
  mavenwebapp:
    image: etishreebehera/maven-web-app:${IMAGE_TAG}
    ports:
    - 7070:8080
    networks:
    - mavenwebappbridge
    restart: always
networks:
  mavenwebappbridge:
    driver: bridge
